### PR TITLE
Added ExternalFQDN parameter for better security.

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

Znuny uses the fully qualified domain name (FQDN SysConfig setting)
for external IDs generation (i.e. Message-ID in e-mail messages,
ContentID for pasted images). If Znuny instance uses internal
domain for FQDN, this internal domain name will leak to third
parties in e-mail message headers which may be not desirable.

This mod introduces new SysConfig option ExternalFQDN which allowes
one to define the fully qualified domain name for external IDs
generation (i.e. Message-ID in e-mail messages, Content-ID for
pasted images).

If ExternalFQDN is not defined in SysConfig (default), Znuny will
still use FQDN setting for Message-ID and ContentID generation.

## Additional information

- We treat internal info leaking as bug so this PR is bugfix not feature in our opinion.
- Author-Change-Id: IB#1009570

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

**Comment by pboguslawski** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

we have changed our rules regarding copyright.
We therefore ask you to remove your newly added copyrights.

```
Znuny is an open fork of an existing software.
So we have to respect the already given copyright of the original creators.

New files will be licensed using the AGPL Version 3. 
If you contribute code to the Znuny project you will get mentioned in the pull request incl. the commit, 
in CHANGES.md and in AUTHORS.md. 
We will not mention you in the file you provided or changed. 
Your work is highly appreciated and acknowledged but you contribute it to the project 
and your copyright will pass on to the fork itself.
```
https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#licensing-copyright-and-credits

**Comment by pboguslawski** [comment]
Done.

**Comment by reneeb** [comment]
It would be great to have this PR in Znuny...

**Review by dennykorsukewitz — APPROVED** [review]

**Comment by dennykorsukewitz** [comment]
Hi @rkaldung ,
 could you please review this pr, too?

**Comment by eyazi** [comment]
Just a minor notice, but I would keep the variable name at $FQDN and not change it to $ExtFQDN.

**Comment by pboguslawski** [comment]
> Just a minor notice, but I would keep the variable name at $FQDN and not change it to $ExtFQDN.

$FQDN parameter name cannot be used here - it is already used for different purposes i.e. obtaining application hostname.

**Comment by rkaldung** [comment]
> Hi @rkaldung ,
> could you please review this pr, too?

Sure. Even when I personally think that's security by obscurity.. At least is it posibble that we add some more characters to give a readable name to this setting like ExternalFQDN oder VisibleFQDN?

**Review by rkaldung — CHANGES_REQUESTED** [review]
@pboguslawski  As mentioned earlier, the name should be speaking for itself. Please use `ExternalFQDN` as the new setting name.

**Comment by pboguslawski** [comment]
Done in 27f7ce0fa76663c6f94b35bd1cc2dda0386b3fd1.

**Review by dennykorsukewitz — APPROVED** [review]

**Pull request merged**
