### PR TITLE
Redundant article search index rebuilding fixed

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

Article search index is rebuild twice:

(1) in ArticleCreate (ArticleSearchIndexBuild called)

and

(2) by FulltextIndexRebuildWorker.pm task called from otrs.Daemon
(because articles are created in article table with default value
in search_index_needs_rebuild column which is 1).

This is waste of resouces and may cause unnecessarry data
fragmentation in search index backends.

This mod resolves this issue by unflagging article for search
index rebuilding after successfull index rebuild.

To be considered for future versions (not included in this mod):
change article.search_index_needs_rebuild default value in DB
schema to 0 to avoid possible races with otrs.Daemon trying to
update article search index just after insert to article table
in ArticleCreate and before ArticleCreate calls
ArticleSearchIndexBuild.

Author-Change-Id: IB#1108194

## Type of change

Change in POD.

- 🆙 - Dependency upgrade (e.g. libraries)
- 🐞 - Bugfix (non-breaking change which fixes an issue)
- [X] 💎 - Code quality improvements to existing code or addition of unit tests
- 🚀 - New feature (which adds functionality to an existing integration)

## Checklist

- [ ] The code change is tested and works locally.(❗)
- [ ] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

we have changed our rules regarding copyright.
We therefore ask you to remove your newly added copyrights.
And also the changes in CHANGES.md

```
Znuny is an open fork of an existing software.
So we have to respect the already given copyright of the original creators.

New files will be licensed using the AGPL Version 3. 
If you contribute code to the Znuny project you will get mentioned in the pull request incl. the commit, 
in CHANGES.md and in AUTHORS.md. 
We will not mention you in the file you provided or changed. 
Your work is highly appreciated and acknowledged but you contribute it to the project 
and your copyright will pass on to the fork itself.
```
https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#licensing-copyright-and-credits

**Comment by pboguslawski** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

**Comment by pboguslawski** [comment]
Replaced by https://github.com/znuny/Znuny/pull/395

**Pull request closed without merging**
