### PR TITLE
BUG fixed: responsible user id isn't set correctly during appointment…

### PR DESCRIPTION
**Pull request by MarcPahnke**
responsible user id isn't set correctly during appointment ticket creation.

This solves https://github.com/znuny/Znuny/issues/324

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [x] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy passed.(❕)
- [x] Local UnitTests / Selenium passed.(❕)
- [x] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

### CODE REVIEW

**Comment by MarcPahnke** [comment]
I hope this will be merged in the upcoming 6.5.x ;-)

**Comment by NiklasSchmitt** [comment]
Hi @MarcPahnke,

thank you very much for your PR.
Please check that your changes compliance to our ZnunyCodePolicy.

Best regards,
Niklas :coffee: :rocket:

**Comment by rkaldung** [comment]
@MarcPahnke Please check the failed CodePolicy step.

**Comment by rkaldung** [comment]
> thank you very much for your PR. Please check that your changes compliance to our ZnunyCodePolicy.


@NiklasSchmitt Please provide a little bit more details what need to be fixed.

**Comment by dignin** [comment]
> > thank you very much for your PR. Please check that your changes compliance to our ZnunyCodePolicy.
> 
> @NiklasSchmitt Please provide a little bit more details what need to be fixed.

@NiklasSchmitt , any updates on this?

**Review by NiklasSchmitt — APPROVED** [review]
I'm sorry for the delay. I've tested and reviewed it today. Approved :rocket:

**Comment by NiklasSchmitt** [comment]
cherry-picked also in Znuny LTS. Will be part of the next Znuny LTS version 6.5.4: https://github.com/znuny/Znuny/commit/ab049def994dadabca7eb5d92072ff3a37d64076

**Pull request merged**
