### PR TITLE
Fixed IMAPS server TLS certificate verification

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

Znuny does not verify IMAPS server TLS certificate, thus IMAPS
connections are not protected against man-in-the-middle attacks.

This mod introduces two SysConfig settings:

    TLS::VerifyPeer
    Allows to enable or disable TLS peer certificate verification.

    TLS::CAPath
    Allows to specify path with trusted CA certs for peer cert
    verification.

Both settings are used now for IMAPS connections.

This mod fixes only IMAPS mail mode for fetching e-mails
from remote IMAP servers to Znuny; there are more places in Znuny
which should be fixed in similar way, i.e. POP3S, POP3TLS,
IMAPTLS mail fetching modules, maybe other Znuny connection
routines if use TLS connections.

Related: http://search.cpan.org/~sullr/IO-Socket-SSL-2.027/lib/IO/Socket/SSL.pod#Common_Usage_Errors
Related: https://github.com/OTRS/otrs/pull/1160/files
Author-Change-Id: IB#1017358

- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

**Comment by pboguslawski** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

we have changed our rules regarding copyright.
We therefore ask you to remove your newly added copyrights.

```
Znuny is an open fork of an existing software.
So we have to respect the already given copyright of the original creators.

New files will be licensed using the AGPL Version 3. 
If you contribute code to the Znuny project you will get mentioned in the pull request incl. the commit, 
in CHANGES.md and in AUTHORS.md. 
We will not mention you in the file you provided or changed. 
Your work is highly appreciated and acknowledged but you contribute it to the project 
and your copyright will pass on to the fork itself.
```
https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#licensing-copyright-and-credits

**Comment by pboguslawski** [comment]
Done.

**Comment by rkaldung** [comment]
@pboguslawski This is PR covers only IMAPS?

**Comment by pboguslawski** [comment]
> This is PR covers only IMAPS?

https://github.com/znuny/Znuny/pull/80#issue-646018334

> This mod fixes only IMAPS mail mode for fetching e-mails
> from remote IMAP servers to Znuny; there are more places in Znuny
> which should be fixed in similar way, i.e. POP3S, POP3TLS,
> IMAPTLS mail fetching modules, maybe other Znuny connection
> routines if use TLS connections.

**Comment by rkaldung** [comment]
@pboguslawski I really like this PR but unless we have the time to add all the other missing pieces we have to pause working on this PR. Please understand that we only add feature/changes when the are "complete". Adding a setting to verify the certifcates of TLS peers suggest that this is used everywhere.

**Comment by rkaldung** [comment]
@pboguslawski Have you considered adding the missing protocols to this PR?

**Comment by pboguslawski** [comment]
> I really like this PR

Strict server cert verification during TLS handshake should be default behaviour in every TLS communication with (dangerous) option to disable it. Lack of such verification should be treated as serious bug IHMO.

> Please understand that we only add feature/changes when the are "complete".

No time resources now to analyze and contribute such fix for other backends sorry. Consider merging this fix for IMAPS and creating issue for future to fix other places it necessary.

**Comment by dennykorsukewitz** [comment]
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

**Comment by dignin** [comment]
Since this PR doesn't cover all inbound protocols, we will close it.

**Pull request closed without merging**
