### PR TITLE
Sector Nord AG: Fixed all missing german translations.

### PR DESCRIPTION
**Pull request by paulfolkers**
## Proposed change

In Znuny 7 there are many german translations missing, which will be available now.

1 - 🐞 bug 🐞

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy passed.(❕)
- [ ] Local UnitTests / Selenium passed.(❕)
- [ ] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

Units tests and code policy are not applicable to this.

### CODE REVIEW

**Comment by dignin** [comment]
Hi @paulfolkers , thanks for helping out here. If you have translation fixes in the future, please translate using the Weblate platform. https://translations.znuny.org/projects/znuny/znuny/de/ This will save you and us time in the long run. I've passed this on and @dennykorsukewitz will contact you if needed.

**Comment by paulfolkers** [comment]
> Hi @paulfolkers , thanks for helping out here. If you have translation fixes in the future, please translate using the Weblate platform. https://translations.znuny.org/projects/znuny/znuny/de/ This will save you and us time in the long run. I've passed this on and @dennykorsukewitz will contact you if needed.

Hi Shawn, didn't know about that, thank you.
Are you able to merge it or should I fill the missing translations at the Weblate platform?

**Comment by dennykorsukewitz** [comment]
Hi @paulfolkers ,

All files under `Kernel/Language/*` are automatically generated from the [`i18n/Znuny/Znuny.*.po`](https://github.com/znuny/Znuny/blob/dev/i18n/Znuny/Znuny.de.po) via 
`bin/otrs.Console.pl Dev::Tools::TranslationsUpdate`.
I can only merge the PR if you also edit the [Znuny.de.po](https://github.com/znuny/Znuny/blob/dev/i18n/Znuny/Znuny.de.po).

But as Shawn said, organizationally we want to separate the translations from the code here.

Anyway, thank you for your PR.
In this one case you may decide whether to extend the PR or use Weblate.
I am OK with both.

Regards :rocket:

**Comment by paulfolkers** [comment]
Hi @dennykorsukewitz, I placed all translation suggestions in Weblate.
I did not create an account for that, we'd be happy if you could just mention Sector Nord AG in your changelog then. ;-)

I will close this PR for now, since this code merge is not necessary now.

**Pull request closed without merging**
