### PR TITLE
improvement/clickable_queue

### PR DESCRIPTION
**Pull request by leon-wolf**
add link to queue in ticket information

## Proposed change
Add HTML-Link to Queue-Name in the Ticket Information Widget. #132 

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by hanneshal** [comment]
Hi @leon-wolf 

thanks for the PR. But I think we wont integrate this at the moment. Mostly because I don't see a value to have another option to go back/ jump to a specific queue. It fits a usecase for small group of users. 
Don't get me wrong, I understand what this is doing. But we would need to modify the service(Serviceview), State and many little other things to be consistent or avoid questions like "but I can click on the queue, why not on XY". 

I really appreciate your effort but I will close this PR. 

I invite you to discuss future PRs, in advance in our discord or in the forum. 

Johannes

**Comment by dpalic** [comment]
Hi Hannes,
instead of rejecting the change a better community driven approach would have been to inform @leon-wolf how to improve.

Hope Znuny is more likely to help and not to evolve like OTRS AG did in the past and lost tons of contributors after the first years.

@leon-wolf I appreciate your change here! Hopefully Znuny will also get more open to help the community to grow and not to kick them in the ass by throwing contributed lifetime into the garbage bin.

**Comment by dpalic** [comment]
> But we would need to modify the service(Serviceview), State and many little other things to be consistent or avoid questions like "but I can click on the queue, why not on XY".

fully unclear, please name the specific use cases to be able to investigate or to improve

**Comment by hanneshal** [comment]
Hi @dpalic 

thanks for the feedback. 
I think a good way to start, before opening a PR is to ask if it is actually a needed feature. And this is not related to our project but to any open source contribution. And my unpopular role here is to manage those requests. Thats one of the reasons we are open for everyone on so many channels. We have a Discord chat, we a forum, we have a dedicated mail address and we have open GitHub Issues. 
Which (in my opinion) are the worst choice to discuss this. Because the possibilities are so limited. No one is able to vote here, discussions are very limited and get out of hand very fast. 

We always discuss PRs and Issues in the team. If one proposes a change, there is a chance that it will not be find it's way into the code. Nothing personal or special here. 

There is an even higher chance, when no one of the actual community has been asked "Hey, I find this useful, what do you think? I could create a PR for this. "

I don't want to make such decisions in the first place, we are happy about everyone using it and contributing. Thats why we started this project in the first place and had a lot of code open before.  But just to take the PR, because it looks useful to you as a contributor, will lead to chaos. Keep in mind, we have to maintain this software. And our resources are not the ones from other projects.  

@leon-wolf if you like to discuss this PR, feel free to start a topic in the discord or in the forum. We are happy to discuss it there.

@dpalic 
To answer your question here:
> > But we would need to modify the service(Serviceview), State and many little other things to be consistent or avoid questions like "but I can click on the queue, why not on XY".
> 
> fully unclear, please name the specific use cases to be able to investigate or to improve
The situation is pretty simple if think about it from a perspective which is not yours. 

@leon-wolf modified the queue name in the ticket information to get a direct link back to the queue-view of the ticket. 
Why stop there? There is a ticket type shown, there is a service shown and (depending on the config) much more. 

All I was pointing out is,  if we accept this PR, we need to think about other, maybe related, changes. 
And we have to think about the user who don't want this to be a link. The ones trying top copy paste a value and click a link by accident. (Ever tried to copy a DynamicField Name from the HTML Table in DF Overview?)

To take care about this we would need another set of sysconfigs and so on... 
It may be simple for you, and you are free to apply this change to your system, but is not that easy if have to answer the user questions in the support. 


And just to address your concerns  @dpalic:
We are the last ones who block Community efforts. Since Nov 1st we even have a dedicated community manager who will take care about Feature Requests and PRs, but needs to get his things sorted first. 
We are the founder and hoster the community forum since the beginning. We wont drop community efforts of any kind.  

Comparing us to the AG is a red flag and not well thought in my personal opinion. It might not all be perfect and as you might expect it, but we try to improve every day.

Regards
Johannes

**Comment by leon-schaefer** [comment]
@hanneshal It's completely ok for me! 👍 Was one of my first open-source contributions. Thanks for the Tip with Discord etc. I just joined it after the PR I think. Next time I will start a discussion about ideas over there first. 

@dpalic i don't have the feeling of being blocked here! In my opinion it is completely legitimate for Znuny to close a PR and I'm really satisfied how Znuny is handling everything. Also I really don't feel kicked in the ass. :D I still learned from it :)

**Comment by dpalic** [comment]
@hanneshal my first important thing is, I was not intending to insult anyone regarding the past time on AG. So sorry if I did this.

I have contributed starting 2005 a lot to OTRS with my team mates and most lifetime got dropped without real clear responses. But making money was on their priorities. So maybe I am a bit badly biased from past. Will improve myself on this, since I really appreciate that OTRS is now really OSS and thus you may have seen I am interested to give feedback from over 15y of usage of OTRS.

Anyway BEFORE closing a issue, and closing it fast (which was done already in my cases) it would be much better to:
1. provide details how to improve
2. wait for a few weeks to get feedback if something is unclear, we do it in spare time of ontop of business requirements
3. inform clearly, and not with nebulous "we need to think about other issues". This will neither help the contributors nor it will help znuny. If there are issues, your team knows them, name them and the contributor will surely be interested to fix them too.

Also in my past career as tech lead we had beta features, which a user could enable (via Settings) on his own risk. This would make it possible to test and collect feedback in stabe versions... And on approval it was a simple flag to remove...

Simply take this as consideration into your team...

**Comment by hanneshal** [comment]
Hi @dpalic 

I think we can agree that we disagree on some points here. One of the things: Issues should not be used for a feature request at all. We need to create a way to handle those request in a way they can be measured, voted and discussed. 
We will come up with something, but give us some time please. 
That's one of the (many) jobs our community manager will handle. 

But thanks for pointing out your view, it is noted. 

We will update our contributing.md for the feature branch, we missed this so far, and will explain more clearly how to contribute.

Regards
Johannes

**Comment by dpalic** [comment]
you can create Feature issues, like other github projects do. I already pushed a feature request on the github and used a template for creation. Maybe some look to other OSS big projects on github could help? Willing to support here

**Pull request closed without merging**
