### PR TITLE
Schedules must be defined in UTC not OTRSTimeZone

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

Znuny cron schedules (i.e. defined in Generic agent jobs or
Daemon::SchedulerCronTaskManager::Task parameters) after
dc8282e00d72b87d1ca39a9559c0e63a0176810b are UTC schedules not OTRSTimeZone
schedules (not elegant but probably better leave this solution now to avoid
daylight savings quirks).

This mod fixes/adds schedule descriptions to explain this.

## Type of change
- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Additional information

Fixes: dc8282e00d72b87d1ca39a9559c0e63a0176810b
Author-Change-Id: IB#1110542

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by felixjogris** [comment]
Hi,

what if we rollback https://github.com/znuny/Znuny/commit/dc8282e00d72b87d1ca39a9559c0e63a0176810b from Kernel/System/CronEvent.pm? https://github.com/znuny/Znuny/commit/5f87d0ebe28e9d590adb21e931ec8c063f27fa68 fixed this whole datetime vs. daylight savings issue. See also my other comment https://github.com/znuny/Znuny/issues/113#issuecomment-956249214

BR,
Felix

**Review by dennykorsukewitz — CHANGES_REQUESTED** [review]
Hi @pboguslawski ,

we will not merge the changes in Kernel/Config/Files/XML/Daemon.xml as it would generate too many translations which are not absolutely necessary at this point.
The explanation to use UTC should be included in the documentation.

So please remove these changes.

`Kernel/Language/pl.pm` 
and 
`Kernel/Output/HTML/Templates/Standard/AdminGenericAgent.tt`
looks good 👍🏼

**Comment by pboguslawski** [comment]
> we will not merge the changes in Kernel/Config/Files/XML/Daemon.xml as it would generate too many translations which are not absolutely necessary at this point.
> The explanation to use UTC should be included in the documentation.

Executing automatic tasks at specific times may be critical; non obvious timezone should be clearly stated in UI not in manual only (do you read manual every time you change param in app that already have reliable description in UI)? Administrators will intuitively believe that times are defined according to OTRSTimeZone and surprises will happen.

Changing descriptions and forcing contributors to translate it again is less pain IHMO.

**Comment by dennykorsukewitz** [comment]
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

**Comment by pboguslawski** [comment]
Replaced by https://github.com/znuny/Znuny/pull/407

**Pull request closed without merging**
