### PR TITLE
Filename cleanup and attachment handling fixes

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

This mod fixes several problems in filename cleanup
and attachment handling:

* filename celanup logice was messy and contained
  obsolete UTF-* filtering,

* if two different filenames were cleaned up to the same
  filename, uploading it failed (with WebUploadCacheModule
   = Kernel::System::Web::UploadCache::FS try to upload files
  test.txt and .test.txt to the same article using agent
  web panel - you'll see broken attachment list,

* mapping attached message/rfc822 message subject to filename
  was not optimal and didn't handle empty subjects well (attachment
  will be named "eml" not similar to "file-N.eml" as it should),

* Ajax UI did not support filename cleanups at server side
  on attachment upload,

* a few uninitialized variables generated errors in apache
  error.log,

* long attachment filenames (i.e. >200 chars) were not fully
  displayed in UI (hidden overflow); no file extension (better
  to display it for security reasons) nor link to download
  was displayed in such cases,

Note:
This mod does not resolve problems with WebUploadCacheModule
= Kernel::System::Web::UploadCache::DB because it'll require
DB schema change (no column for original filename in SQL
web_upload_cache table available now); uploading
long filenames (i.e 0123456ąćę111110123456ąćę0123456ąćę01234
56ąćę0123456ąćę0123456ąćę0123456ąćę0123456ąćę0123456ąćę01234
56ąćę0123456ąćę0123456ąćę0123456ąćę0123456ąćę0123456ąćę01234
56ąćę0123456ąćę0123456ąćę0123456ąćę0123456ąćę0123456ąćę01234
56ąćę0123456ąćę0123456ąćę005.txt) will generate broken
attachment list and sending such article will generate ugly
trimmed attachement filename.

Related: https://github.com/OTRS/otrs/pull/1181
Related: https://github.com/OTRS/otrs/pull/1959
Author-Change-Id: IB#1016067

## Type of change
- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [x] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

**Comment by pboguslawski** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

**Comment by pboguslawski** [comment]
Replaced by https://github.com/znuny/Znuny/pull/374

**Pull request closed without merging**
