### PR TITLE
Fixed mentions for deleted tickets.

### LINKED ISSUE #459: Bug – Deleting a ticket leaves mentions behind.
### Environment

- OS:           any
- Browser:      any
- Znuny version: Znuny LTS 6.5 and Znuny 7

### Expected behaviour

A mention should be deleted, if the ticket is deleted.

### Actual behaviour

If users are mentioned in a ticket, and the ticket is deleted, then the mentoin remains.

### How to reproduce

1. Mention a user in a ticket.
2. Delete the ticket.
3. Notice the mention is still shown for the user.

```
bin/otrs.Console.pl Maint::Ticket::Delete --ticket-id 1

MariaDB [znuny]> select * from mention\G
*************************** 1. row ***************************
         id: 1
    user_id: 2
  ticket_id: 1
 article_id: 3
create_time: 2023-07-07 06:12:23
1 row in set (0.001 sec)

MariaDB [znuny]> select ticket_id from mention where ticket_id not in (select id from ticket);
+-----------+
| ticket_id |
+-----------+
|         1 |
+-----------+
1 row in set (0.001 sec)
```

### Screenshots

Snag_34abb13

### PR DESCRIPTION
**Pull request by tipue-dev**
## Proposed change

Currently Mentions, that are linked to a ticket, don't get removed when the ticket is deleted.
Without a ticket, the Mentions can't be removed anymore by an agent.
image
This change removes all Mentions from a ticket when it gets deleted.

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy passed.(❕)
- [ ] Local UnitTests / Selenium passed.(❕)
- [x] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
Please don't forget a migration module for the cleanup of existing orphans.

**Comment by tipue-dev** [comment]
> Please don't forget a migration module for the cleanup of existing orphans.

This is my first time in that corner of the code. If i should make something differently let me know

**Comment by tipue-dev** [comment]
Not ready yet, i have to fix something

**Comment by tipue-dev** [comment]
Tested the migrations script, it's working now too

**Review by dennykorsukewitz — APPROVED** [review]
Hi  @tipue-dev ,
thanks for your PR.

Approved :+1:

Regards :rocket:

**Pull request merged**
