### PR TITLE
Added events for article email backend transmission errors.

### PR DESCRIPTION
**Pull request by reneeb**
## Proposed change

Until now, no one notices when a transmission error occurs and the ticket
is closed. With the new events it is possible to create GenericAgent jobs
that listens for the transmission error events and tickets can be re-opened
automatically.

## Type of change

- '1 - 🚀 feature'           - New feature (which adds functionality to an existing integration)

## Additional information

- This PR is related to forum thread https://community.znuny.org/viewtopic.php?f=34&t=42765

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Review by dennykorsukewitz — COMMENTED** [review]
Hi @reneeb,

looks good so far.
I was wondering if we could catch the events in the tests and check if they were triggered correctly.

- [ ] extend UnitTest [ArticleCreateTransmissionError](https://github.com/znuny/Znuny/blob/dev/scripts/test/Ticket/Article/Backend/TransmissionLog.t#L100)
- [ ] extend UnitTest [ArticleUpdateTransmissionError](https://github.com/znuny/Znuny/blob/dev/scripts/test/Ticket/Article/Backend/TransmissionLog.t#L117)

I am also thinking about the names of the events. Maybe they should have the same name as the name of the function. That would be a bit clearer.
What do you think @jepf

```
ArticleTransmissionErrorCreate => ArticleCreateTransmissionError
ArticleTransmissionErrorUpdate => ArticleUpdateTransmissionError
```

**Comment by reneeb** [comment]
I used that names as (almost) all events use that scheme: <What><Action> (e.g. ArticleCreate, TicketOwnerUpdate, ...). But feel free to rename the events.

I'll have a look at unittests next week.

**Comment by dennykorsukewitz** [comment]
Hi @reneeb 

> I used that names as (almost) all events use that scheme: (e.g. ArticleCreate, TicketOwnerUpdate, ...). But feel free to rename the events.

Yes, I have seen that.  
It's just a consideration at the moment.


> I'll have a look at unittests next week.

Nice 👍🏼  🚀

**Review by dennykorsukewitz — APPROVED** [review]
👍🏼 Yes 👍🏼

**Comment by jepf** [comment]
@reneeb 

Thank you!

**Pull request merged**
