### PR TITLE
 Fixed evaluation of parameter TicketID in Kernel::Output::HTML::Article::Base::ArticleActions (by maxence).

### PR DESCRIPTION
**Pull request by LotharZok**
## Proposed change

Trigger was that we wanted to hide the print button in articles via ACL. This worked well in an open Ticket. However, in the Ticket Overview, e.g. by Queue, the print button was still visible in the large view.

I found the reason for this in module Article/Base.pm. Here in "sub ArticleActions" it is checked whether an ACL is active. The Ticket ID is passed here as follows:
```TicketID => $Param{Ticket}->{TicketID},```

The problem is that this parameter is passed when displaying an open ticket, but not when displaying a Ticket Overview. Therefore the print button for a ticket (or its article) is not hidden (see screenshot).
Screenshot-1

In the call of the function "sub ArticleActions", however, it is checked whether the TicketID is passed as a parameter:
```for my $Needed (qw(TicketID ArticleID Type UserID)) {```

This means that the TicketID is present in any case, because otherwise the function is cancelled.

I therefore suggest changing the line stated above as follows:
```TicketID => $Param{TicketID},```

With this setting, the ACL will be taken into account in the Ticket Overview, i.e. the print button will be hidden (see screenshot).
Screenshot-2

1 - 🐞 bug 🐞
## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
@LotharZok I tried to reproduce the behavior with Znuny 6.4. But the ACL worked as expected. Removing the action AgentTicketPrint (and others) with an ACL also worked M and L view. Did I missed sth?

**Comment by eyazi** [comment]
@rkaldung You probably did not set match settings for ticket attributes.

If your ACL looks like this, the print button gets removed in AgentTicketStatusView and in AgentTicketZoom.
  ConfigChange → PossibleNot → Action → AgentTicketPrint

If your ACL looks like this, the print button will get removed in AgentTicketZoom, but not in AgentTicketStatusView.
  ConfigMatch → Properties → Ticket → Queue → '[RegExp].*'
  ConfigChange → PossibleNot → Action → AgentTicketPrint

**Comment by rkaldung** [comment]
@eyazi You're right, thank you.

**Comment by rkaldung** [comment]
@jepf Could be verified including the solutions

**Comment by LotharZok** [comment]
Sorry, I was offline for a few days. @eyazi is right, I had set a match setting.

**Review by jepf — APPROVED** [review]

**Comment by jepf** [comment]
@LotharZok 

Thank you!

**Pull request merged**
