### PR TITLE
Sector Nord AG: Fixed popup description long were cut off in Customer Interface.

### PR DESCRIPTION
**Pull request by jross93**
## Proposed change

In the customer portal the hover popup "description long" will be cut off if it is set for the first field.

image

## Type of change

- '1 - 🐞 bug 🐞'

## Additional information

* It only happens in the customer portal.
* It only happens for the first field.

I identified the CSS setting in `var/httpd/htdocs/skins/Customer/default/css/Core.Form.css`:
```css
fieldset h2 + div {
    padding-top: 13px;
    border-top: 1px solid #FFF;
    overflow: hidden;
}
```

I think the `overflow: hidden` doesn't make sense here, because it was only used for the first field in the field list so far.

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy passed.(❕)
- [ ] Local UnitTests / Selenium passed.(❕)
- [x] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

### CODE REVIEW

**Comment by dennykorsukewitz** [comment]
Hi  @jsinagowitz ,
thanks for your report.

> It only happens in the customer portal.
> It only happens for the first field.


I cannot reproduce this error.
Can you please export a process that contains this error?

Process_ticket_-_Ticket_-_znuny_dev

@NiklasSchmitt Can you confirm this or can you reproduce the error?

Please, keep your fork up-to-date with the upstream repository. 
[Syncing a fork 🚀  🆙 ](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)

Regards :rocket:
Denny

**Comment by NiklasSchmitt** [comment]
I can not reproduce this reported behavior. I've added a very very long Lorem ipsum-string into "description long" for the first field and it's all to see into customer portal and also on agent portal.
grafik

**Comment by jross93** [comment]
I did some more research. I think you can't reproduce that because of the description in the dialog. You might need to remove that.

image

The "wrong" css setting is only active, if the div-tag of the first field follows the h2-tag directly.

image

```
$('fieldset h2 + div')
```

If you can't reproduce that eather I will send you my process. I can reproduce the bug on multiple systems.

**Comment by NiklasSchmitt** [comment]
Hi @jsinagowitz,

thank you for your additional information. I was able to reproduce the issue and I want to accept & merge your pull-request. Bur first: Please, keep your fork up-to-date with the upstream repository. [See here](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) how to sync a fork.

Best regards,
Niklas Schmitt :coffee: :rocket:

**Review by NiklasSchmitt — APPROVED** [review]

**Pull request merged**
