### PR TITLE
Added 'AdditionalSearchParameters' to Toolbar TicketSearchFulltext  to define the standard search more precisely.

### PR DESCRIPTION
**Pull request by tipue-dev**
## Proposed change
Currently the full text search from the toolbar searches trough all tickets. I assume that most agents who want to use this are looking for open tickets. 
If this change is not wanted, i would propose to add a config entry to exclude closed tickets from the full text search toolbar.

1 - 🚀 feature
## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by dennykorsukewitz** [comment]
Hi @tipue-dev 

"I assume that most agents who want to use this are looking for open tickets."

I am sorry, but you can't assume that. 😄  
The system is used by so many different companies and industries. 
Believe me, you have to expect everything. 😆 

I cannot accept this PR in this way.

If you have an idea how we can make this dynamic / configurable, we can talk about it again.

Thank you for your efforts. 
:rocket:

**Comment by tipue-dev** [comment]
Hey @dennykorsukewitz,

> If you have an idea how we can make this dynamic / configurable, we can talk about it again.

Maybe this would be an acceptable solution. The current functionality is not changed, but one can add parameters as needed.

**Comment by dennykorsukewitz** [comment]
Hi @tipue-dev,

I have also imagined this in the same way.
I will check the changes next week.

👍🏼

**Review by dennykorsukewitz — APPROVED** [review]
👍🏼 Perfect, that's how I imagined it.

**Pull request merged**
