### PR TITLE
fix [#16]: GenericInterface - ticket with less articles then the give…

### PR DESCRIPTION
**Pull request by reneeb**
…n article limit has effect on subsequent ticket

Given ticket 1 has 7 articles and ticket 2 has 12 articles and an article limit is set (e.g. to 100). When
a webservice endpoint is called to get tickets 1 and 2, only 7 articles are shown. This fix checks the
article limit and the articles in the ticket for each ticket.

### CODE REVIEW

**Comment by reneeb** [comment]
I'll provide a unittest this afternoon...

**Review by jepf — APPROVED** [review]

**Comment by jepf** [comment]
@reneeb 

Thank you very much. Your fix will be part of release 6.0.33.

**Comment by dennykorsukewitz** [comment]
Hi,

Due to internal filtering there was a change to the CommitIDs.
This was discussed in this issue: https://github.com/znuny/Znuny/issues/13

We have decided not to use filtering anymore so that the CommitID are original again.
To achieve this we had to perform a force push.
Because of this the forks are now out of sync with znuny/Znuny.
Please rebase the forks / branches from rel-6_0 and also the PR.

best regards
Znuny :rocket:

**Comment by jepf** [comment]
@reneeb 

Is it OK if we change the license of your new unit test file to AGPL?

**Comment by reneeb** [comment]
@jepf Sure. I'll change that after the rebase...

**Comment by reneeb** [comment]
Something did go wrong during rebase. I'll close this PR and create a new one...

**Pull request closed without merging**
