### PR TITLE
Feature request: Automatic transfer of the ticket title to the note heading

### PR DESCRIPTION
**Pull request by schnudd31do3**
## Proposed change

When one create a note, either a fixed value is used or the heading is empty. With this extension, the subject line can also be automatically inserted into the note heading. The previous functionality is not changed.

In order to use this, the value "[% Data.Title %]" must be entered ​​in the sysconfig in the following settings:

- Ticket::Frontend::AgentTicketNote###Subject
- Ticket::Frontend::AgentTicketClose###Subject
- Ticket::Frontend::AgentTicketOwner###Subject
- Ticket::Frontend::AgentTicketPending###Subject
- Ticket::Frontend::AgentTicketPriority###Subject

To achieve this, three places in the source code need to be expanded with "**Data => \%Ticket,**" in https://github.com/znuny/Znuny/blob/dev/Kernel/Modules/AgentTicketActionCommon.pm. 

Insert near line 1069:

`

                if ( $Config->{Subject} ) {
                    my $Subject = $LayoutObject->Output(
                        Template => $Config->{Subject},
                        Data => \%Ticket,
                    );
                    $GetParam{Subject} = $Subject;
                }

`
and near line 1620:

`

        # fillup configured default vars
        if ( $Body eq '' && $Config->{Body} ) {
            $Body = $LayoutObject->Output(
                Template => $Config->{Body},
                Data => \%Ticket,
            );

`
and near line 1654:

`

        elsif ( !defined $GetParam{Subject} && $Config->{Subject} ) {
            $GetParam{Subject} = $LayoutObject->Output(
              Template => $Config->{Subject},
              Data => \%Ticket,
            );

`
## Type of change

- '1 - 🚀 feature'           - New feature (which adds functionality to an existing integration)

## Additional information

The change is compatible with all versions Znuny. Tested under real conditions for months.

## Checklist

- [X] The code change is tested and works locally.(❗)
- [X] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by dennykorsukewitz** [comment]
Hi @schnudd31do3,

Please check your pull request. 
Something is wrong here!

Added_an_automatic_transfer_of_the_ticket_title_to_the_note_heading_by_schnudd31do3_·_Pull_Request__195_·_znuny_Znuny

**Comment by schnudd31do3** [comment]
I am new to the procedure. Could you please help me what to do? Or is it possible for you to correct it for me?

**Comment by schnudd31do3** [comment]
Hi dennykorsukewitz,
I corrected it. It was not on purpose. What are the next steps to complete my pull request? I don't want my pull request to be rejected because of some formal error.

**Comment by rkaldung** [comment]
@schnudd31do3 Please check your PR again. You try to merge our rel-6_2 into our rel-6_2-dev. Please use always the dev branch as the starting point to fork and create your pull request against the dev branch. For more details there is a nice manual from GitHub: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

Besides the fact that your change is pretty static and only allows the ticket title I suggest to change https://github.com/znuny/Znuny/blob/dev/Kernel/Modules/AgentTicketActionCommon.pm#L1654 at least into something like this:

```
$GetParam{Subject} = $LayoutObject->Output(
  Template => $Config->{Subject},
  Data => \%Ticket,
);
```

This provides access to the complete ticket hash:
image

Same is possible for the Body, line here is https://github.com/znuny/Znuny/blob/dev/Kernel/Modules/AgentTicketActionCommon.pm#L1620

**Comment by schnudd31do3** [comment]
Hi rkaldung,

thanks for you friendly suggest. I will check it. Please wait for my reply.

**Comment by schnudd31do3** [comment]
Hello Roy,

this is great and is exactly what I need. Your solution is much better than mine. Should I change my pull request based on your suggestion?

**Comment by rkaldung** [comment]
> Hello Roy, this is great and is exactly what I need. Your solution is much better than mine. Should I change my pull request based on your suggestion?

This would be great! Do you think you could also patch the other occurrences for this?

**Comment by schnudd31do3** [comment]
I updated my pull request. I found three places in summary in the AgentTicketActionCommon.pm file. I will need some time to check. Pleasw wait a little.

**Comment by dennykorsukewitz** [comment]
Hi @schnudd31do3 ,

that's great.
Unfortunately, we don't see any of your changes.

Please take another close look at the screenshot.

Added_an_automatic_transfer_of_the_ticket_title_to_the_note_heading_by_schnudd31do3_·_Pull_Request__195_·_znuny_Znuny

`You try to merge our rel-6_2 into our rel-6_2-dev. `
So we will never be able to see your changes.

# Plan B
1. Go to your FORK https://github.com/schnudd31do3/Znuny
2. Fetch the latest commits (see screenshot)
dennykorsukewitz_Znuny__Znuny_Znuny_LTS_is_a_fork_of_the___OTRS___Community_Edition__one_of_the_most_flexible_web-based_ticketing_systems_used_for_Customer_Service__Help_Desk__IT_Service_Management_

3. Create a new Branch from dev (e.g. dev-my-feature)
4. Commit and push all your changes to this branch (GitHub)
5. Create a new PullRequest via GitHub https://github.com/znuny/Znuny/compare/dev...schnudd31do3:dev
Pull_requests_·_schnudd31do3_Znuny

DestinationBranch is `dev`
Source is your new branch e.g. `dev-my-feature`

best 🚀

**Comment by schnudd31do3** [comment]
I checked the new extension (thanks to rkaldung) and found it to work as expected and I didn't see any incorrect behavior.

@dennykorsukewitz:
Thanks for your verry detailed "Plan B". But https://github.com/schnudd31do3/Znuny only offers rel-6_0-dev to me as latest version. I would like to be able to bring my change into 6.2-dev

It's now clear to me that I shouldn't have chosen a pull request, but should have entered my contribution under "Issues". How can I change that? Perhaps closing this and create a new isssue?

**Comment by dennykorsukewitz** [comment]
Hi @schnudd31do3,

I think your contribution is great.
The beginning is always hard 😃  So don't give up. 💪🏼 

If you have done `2. fetch the latest commits (see screenshot)`, then you will also see the new branches.

It is important that you always start from `dev`.

You can also write to me via Discord, then I will help you directly.

Kind regards 🚀

**Comment by schnudd31do3** [comment]
Hello,

I tried to
unfortunately „Plan B“ is not working as shown:
***@***.***


Plan C:
Is it better to shift my pull request to „Issues“?

**Comment by dennykorsukewitz** [comment]
Hi @schnudd31do3 

okay than...let's go **plan C**. 

1. Create a new issue.
2. mention @rkaldung in the new issue.
3. add a link to this PullRequest in the Issue

I will close this PR.

Thank you. 🚀

**Comment by schnudd31do3** [comment]
Hi,
I am really close to give up. I saw you closed the PR. It is OK for me. But for the next time I do not know how exactly to a pull request. My view allways looked different from your screenshots. Never mind, in future I ever will use the issue for contribution tot he project.

Thanks for your patient and excellent support till now.

Best.

**Comment by schnudd31do3** [comment]
Hi @rkaldung<https://github.com/rkaldung>,

I did as you suggested.

Regards.

**Pull request closed without merging**
