### PR TITLE
Fixed LDAP user sync.

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

Fixes undef/empty string comparisons that may occur between data
stored in DB and data coming from LDAP; i.e. if phone number
coming from LDAP is undef, should not cause SQL update if
already undef/empty.

This mod also disallows setting UserType as user preference
(similar to other native data) and protects UserUpdate()
called from LDAP sync routine from touching properties other
than specified in LDAP sync map (to avoid problems if other
User* keys are/will be present in %UserData that are not
user preferences).

## Type of change
- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Additional information

- Author-Change-Id: IB#1014533

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
Hi @pboguslawski,

Thank you for this pull request. I will check the **functionality** and get back to you. In the meantime, please update your PR regarding by using our template and remove the CHANGE.md from them. This file is generated in another way.

**Comment by pboguslawski** [comment]
> by using our template

No time for analysing templates now sorry.  If something is not clear in existing description let me know.

> and remove the CHANGE.md from them

Done.

Regards,
Paweł

**Comment by rkaldung** [comment]
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

**Comment by pboguslawski** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

we have changed our rules regarding copyright.
We therefore ask you to remove your newly added copyrights.

```
Znuny is an open fork of an existing software.
So we have to respect the already given copyright of the original creators.

New files will be licensed using the AGPL Version 3. 
If you contribute code to the Znuny project you will get mentioned in the pull request incl. the commit, 
in CHANGES.md and in AUTHORS.md. 
We will not mention you in the file you provided or changed. 
Your work is highly appreciated and acknowledged but you contribute it to the project 
and your copyright will pass on to the fork itself.
```
https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#licensing-copyright-and-credits

**Comment by pboguslawski** [comment]
Done.

**Review by rkaldung — APPROVED** [review]

**Review by dennykorsukewitz — APPROVED** [review]

**Pull request merged**
