### PR TITLE
Fixed "Invalid date/time string" errors in otrs.Daemon.pl.

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

Fixes errors like:

```
ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker-4 Perl: 5.32.1 OS: linux Time: Sat Oct 22 06:55:00 2022

 Message: Invalid date/time string .

 Traceback (719399):
   Module: Kernel::System::DateTime::_StringToHash Line: 1770
   Module: Kernel::System::DateTime::_CPANDateTimeObjectCreate Line: 1827
   Module: Kernel::System::DateTime::new Line: 153
   Module: Kernel::System::ObjectManager::_ObjectBuild Line: 307
   Module: Kernel::System::ObjectManager::Create Line: 242
   Module: Kernel::System::Daemon::SchedulerDB::TaskCleanup Line: 586
   Module: Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker::PostRun Line: 309
   Module: (eval) Line: 347
   Module: main::Start Line: 347
   Module: /opt/otrs/bin/otrs.Daemon.pl Line: 163

ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker-4 Perl: 5.32.1 OS: linux Time: Sat Oct 22 06:55:00 2022

 Message: Invalid value for String: .

 Traceback (719399):
   Module: Kernel::System::DateTime::_CPANDateTimeObjectCreate Line: 1829
   Module: Kernel::System::DateTime::new Line: 153
   Module: Kernel::System::ObjectManager::_ObjectBuild Line: 307
   Module: Kernel::System::ObjectManager::Create Line: 242
   Module: Kernel::System::Daemon::SchedulerDB::TaskCleanup Line: 586
   Module: Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker::PostRun Line: 309
   Module: (eval) Line: 347
   Module: main::Start Line: 347
   Module: /opt/otrs/bin/otrs.Daemon.pl Line: 163

ERROR: OTRS-otrs.Daemon.pl - Daemon Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker-4 Perl: 5.32.1 OS: linux Time: Sat Oct 22 06:55:00 2022

 Message: Error creating DateTime object ( 'String' => '' ).

 Traceback (719399):
   Module: Kernel::System::DateTime::new Line: 175
   Module: Kernel::System::ObjectManager::_ObjectBuild Line: 307
   Module: Kernel::System::ObjectManager::Create Line: 242
   Module: Kernel::System::Daemon::SchedulerDB::TaskCleanup Line: 586
   Module: Kernel::System::Daemon::DaemonModules::SchedulerTaskWorker::PostRun Line: 309
   Module: (eval) Line: 347
   Module: main::Start Line: 347
   Module: /opt/otrs/bin/otrs.Daemon.pl Line: 163
```

## Type of change
- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Additional information
Author-Change-Id: IB#1125787## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy passed.(❕)
- [x] Local UnitTests / Selenium passed.(❕)
- [ ] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

### CODE REVIEW

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

please, keep your fork up-to-date with the upstream repository. 
[Syncing a fork 🚀  🆙 ](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)

`Some checks were not successful`

Thank you,
Denny

**Comment by pboguslawski** [comment]
> `Some checks were not successful`

Seems your `rel-6_0-dev` CI is broken (wants to call `otrs.CodePolicy.pl` but [you've changed](https://github.com/znuny/ZnunyCodePolicy/tree/dev/bin) test script name to `znuny.CodePolicy.pl`):

```
/__w/_temp/7d26ca5c-484c-423a-ab20-e2e6a7ff2c79.sh: 2: /__w/_temp/7d26ca5c-484c-423a-ab20-e2e6a7ff2c79.sh: codepolicy/bin/otrs.CodePolicy.pl: not found
Error: Process completed with exit code 127.
```

**Comment by dennykorsukewitz** [comment]
Hi  @pboguslawski ,
thanks for your report.

> Seems your `rel-6_0-dev` CI is broken (wants to call `otrs.CodePolicy.pl` but [you've changed](https://github.com/znuny/ZnunyCodePolicy/tree/dev/bin) test script name to `znuny.CodePolicy.pl`):

Yeah, we have changed the codepolicy.
I add another reference for the rel-6_0 version.

Regards :rocket:
Denny

**Comment by pboguslawski** [comment]
> add another reference for the rel-6_0 version.

Our CI in rel-6_0 based on ZnunyCodePolicy version https://github.com/znuny/ZnunyCodePolicy/commit/9741382e5d45afcca161e17d95c665e4eaa888d2 does not thow any errors with this mod.

**Comment by dennykorsukewitz** [comment]
https://github.com/znuny/Znuny/commit/5caaaf93eabfa32aae94bfe556e7bffd6626a91d

**Comment by dennykorsukewitz** [comment]
@pboguslawski please sync again.

**Comment by pboguslawski** [comment]
Done.

**Review by dennykorsukewitz — APPROVED** [review]

**Pull request merged**
