### PR TITLE
Fix missing session parameters if session cookies are disabled

### PR DESCRIPTION
**Pull request by tipue-dev**
## Proposed change

Some action in the frontend open the login page instead of what was requested, if the use of cookies is disabled.
I added the session name and session id as parameter where i found them to be missing.

## Type of change

-  🆙 - Dependency upgrade (e.g. libraries) 
- [x] 🐞 - Bugfix (non-breaking change which fixes an issue) 
-  💎 - Code quality improvements to existing code or addition of unit tests 
-  🚀 - New feature (which adds functionality to an existing integration) 

## Additional information

To reproduce the bug, set the setting "SessionUseCookie" to false.
Try to download the support package using the web interface.

<details>
  <summary>Details to reproduce each error (click to expand)</summary>
  
### File
var/httpd/htdocs/js/Core.SystemConfiguration.js

#### Problem

Changes from line: 192

index.pl?Action=AdminSystemConfiguration;

On the left side in the navigation widget, hover with the mouse over an entry and click on the 
icon, that pops up to open the node in a new window

Problem: Login page is shown

#### Problem

Changes from line: 1624

index.pl?Action=AdminSystemConfiguration;

On the left side in the navigation widget, click on a node.
Then click on the new entry in the breadcrumb.

Problem: Login page is shown

### File
var/httpd/htdocs/js/Core.Agent.Admin.SupportDataCollector.js

#### Problem

Changes from line: 1624

index.pl?Action=AdminSupportDataCollector;

Click on the left on "Generate Support Bundle" and after that on "Download" in the dialog.

Problem: Login page is shown

### File
var/httpd/htdocs/js/Core.Agent.Admin.CommunicationLog.js
#### Problem

Changes from line: 106

index.pl?Action=AdminCommunicationLog;

On the left, change the value of "Time Range" [#TimeRange]

Problem: Login page is shown
#### Problem

Changes from line: 121

index.pl?Action=AdminCommunicationLog;Subaction=Accounts;

On the left, change the value of "Time Range" [#TimeRangeAccounts]

Problem: Login page is shown
#### Problem

Changes from line: 136

index.pl?;Action=AdminCommunicationLog;

select a communicatiob from a status status.
Change the priority filter on the left.

Problem: Login page is shown

### File
Znuny/var/httpd/htdocs/js/Core.Agent.AppointmentCalendar.js
#### Problem

Changes from line: 510

index.pl?Action=AgentAppointmentCalendarOverview;

Create an entry in the calendar.
Open the overview or change the visibility of a calendar.

Problem: Login page is shown
  
</details>

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by dennykorsukewitz** [comment]
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

**Comment by tipue-dev** [comment]
@dennykorsukewitz in case you assign me to remind me about the conflicts, i already resolved them

**Comment by dignin** [comment]
@dennykorsukewitz is this ready to be merged? If so, please do so. Thx.

**Comment by NiklasSchmitt** [comment]
Hi @tipue-dev, could you please try to explain me, how you have found the modules and requests where the session parameters was missing?

**Comment by hanneshal** [comment]
Hi Tim,

sorry, to bother but this cam just up in my feed. 
This "feature" or support for session id in the url is deprecated since the dark ages. 

We wont make any changes to it except for removing it completly. 
The config has to match the environment, otherwise it simply wont work.

Regards
Johannes

**Pull request closed without merging**
