### PR TITLE
Added SysConfig option to enable week numbers in the datepicker widget.

### PR DESCRIPTION
**Pull request by reneeb**
## Proposed change

Currently the datepicker (e.g. to select the pending reminder date/time) shows only the month and its dates. 

image

But in many environments people talk about "this has to be done in week 22...". This change adds a new sysconfig option and when this option is enabled, the datepicker also shows the weeknumber

image

## Type of change

- '1 - 🚀 feature'           - New feature (which adds functionality to an existing integration)

## Checklist

- [X] The code change is tested and works locally.(❗)
- [X] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
@reneeb Is it possible to have different calculation for the calendar weeks? ISO vs. North-American and Arabic style?

**Comment by reneeb** [comment]
You would have to write the function and pass the option `calculateWeek`. jquery-ui datepicker doesn't provide any other method than the default one: https://api.jqueryui.com/datepicker/#option-calculateWeek

**Comment by rkaldung** [comment]
Besides a German translation for the system configuration fine for me.

**Review by rkaldung — APPROVED** [review]
Besides a German translation for the system configuration, this PR is approved.

**Review by dennykorsukewitz — APPROVED** [review]

**Pull request merged**
