### PR TITLE
Fixed package category for iCal-Parser on Gentoo.

### PR DESCRIPTION
**Pull request by tgurr**
## Proposed change
Fix package category for iCal-Parser on Gentoo, actually the package doesn't exist at all on Gentoo yet (pending PR: https://github.com/gentoo/gentoo/pull/30972), but Perl packages usually go to [dev-perl](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-perl) instead of [perl-core](https://gitweb.gentoo.org/repo/gentoo.git/tree/perl-core).

## Type of change
- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Breaking change
-

## Additional information
-

## Checklist

- [ ] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy passed.(❕)
- [ ] Local UnitTests / Selenium passed.(❕)
- [ ] GitHub workflow CI (UnitTests / Selenium) passed.(❗)

### CODE REVIEW

**Comment by tgurr** [comment]
Package has been accepted/merged in Gentoo as `dev-perl/iCal-Parser`:
* https://packages.gentoo.org/packages/dev-perl/iCal-Parser
* https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-perl/iCal-Parser?id=172471ece70ff2077811e672039bb87f48845040

**Comment by rkaldung** [comment]
@tgurr Thank you for this PR. Just some time needed to verify.

**Comment by rkaldung** [comment]
Confirmation via https://wiki.gentoo.org/wiki/Perl

**Review by jepf — APPROVED** [review]

**Comment by jepf** [comment]
@tgurr 

Thank you!

**Pull request merged**
