### PR TITLE
Sector Nord AG: Added support for HTML content of dynamic fields to transition action TicketCreate (analog to TicketArticleCreate).

### PR DESCRIPTION
**Pull request by LuBroering**
## Proposed change

It is not possible to use HTML content of dynamic fields in TicketCreate. This change makes it possible to use HTML content for dynamic fields in the TicketCreate, as it is already possible in the TicketArticleCreate. 

1 - 🐞 bug 🐞

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [x] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
@LuBroering Two questions from my side:

- How does this change affect existing transition action? Might there be a different result?
- Does your change only cover the TicketCreate or all article creating transition actions?

**Comment by LuBroering** [comment]
@rkaldung 
for Example: 
1. Field is a <OTRS_TICKET_DynamicField_TextArea> 
2. Field is a <OTRS_FIRST_ARTICLE_Body>
both fields contain: 
test
test
test
this is how it currently looks like:
grafik
with the propsed change both contents would have the same Format. Like we already have it in TicketArtikleCreate.

This Change only covers TicketCreate. I did not recheck all transition action and just adapted an already existing feature from TicketArtikleCreate into TicketCreate.

**Review by jepf — APPROVED** [review]

**Comment by jepf** [comment]
@LuBroering 

Thank you!

**Comment by Tronsy** [comment]
Hi @LuBroering, 
Unfortunately, I have some problems with the technical QA of the pull request.
Can you please describe the old and the new expected behavior?
Preferably also the "how to reproduce" step by step.

The background is that I cannot create simple line breaks with a DynamicField TextArea even in the TicketArticleCreate Action. That's why I would like to recreate this in order to be able to better assess and check the PR.

**Comment by LuBroering** [comment]
Hi @Tronsy,
First you need to create a process with a TransitionAction 'TicketCreate'.
Then you should fill the Body of the TransitionAction with Placeholder like this: 
grafik
Both fields contain the same content:
test
test
test
A Content with HTML Content in this case it would be the line breaks.

Before it would result in two different Outputs like shown above. After the PR it will result in the same Output like expected.
This feature is analog to the already existing one in the TransitionAction TicketArticleCreate.

**Pull request merged**
