### PR TITLE
Fix bug in _UserCacheClear in Kernel::System::User

### PR DESCRIPTION
**Pull request by ymyasoedov**
FirstnameLastnameOrder setting value can be in range from 0 to 9.

### CODE REVIEW

**Comment by jepf** [comment]
Thank you for your pull request. We'll have a look at it.

**Comment by dennykorsukewitz** [comment]
Hi @ymyasoedov,

can you please change the target branch from **znuny:rel-6_0_dev** to **znuny:rel-6_0.**
The branch **znuny:rel-6_0_dev** was currently only a test branch and will be deleted afterwards.

Thanks for you support. :rocket:

**Comment by ymyasoedov** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Will be merged into version rel-6_0_33.

**Comment by dennykorsukewitz** [comment]
Hi,

Due to internal filtering there was a change to the CommitIDs.
This was discussed in this issue: https://github.com/znuny/Znuny/issues/13

We have decided not to use filtering anymore so that the CommitID are original again.
To achieve this we had to perform a force push.
Because of this the forks are now out of sync with znuny/Znuny.
Please rebase the forks / branches from rel-6_0 and also the PR.

best regards
Znuny :rocket:

**Comment by ymyasoedov** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Fixed in https://github.com/znuny/Znuny/commit/c1b5453a2e396b98ce3d56c2a4a76ab58fad2ad6

👍🏼 🚀

**Pull request closed without merging**
