### PR TITLE
Improvements for Dev::Code::CPANUpdate (#38).

### PR DESCRIPTION
**Pull request by reneeb**
## Proposed change

The current version of the console command Dev::Code::CPANUpdate is not that helpful as it upgrades only two modules.

This change adds a "check" mode that checks the installed vs. available versions of bundled modules (whatever is defined as bundled modules in Kernel::System::Environment):

image

The second mode that was added is "single" to upgrade a single cpan dependency:

image

But you can pass more than one module name.

## Type of change

- [X] 🚀 - New feature (which adds functionality to an existing integration)

## Checklist

- [X] The code change is tested and works locally.(❗)
- [ ] There is no commented out code in this PR.(❕)
- [x] You improved or added new unit tests.(❕/❗depends on the code)
- [ ] Local ZnunyCodePolicy run passes successfully.(❗)
- [ ] Local unit tests pass.(❗)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Review by jepf — CHANGES_REQUESTED** [review]
@reneeb 

Thank you, nice feature 👍 

1. When giving mode "development", message "Error: please provide a valid value for option '--mode'." is shown.
2. When giving mode "single", presence of option "module" should be checked, otherwise error message "Error: Not an ARRAY reference at znuny/Kernel/System/Console/Command/Dev/Code/CPANUpdate.pm line 100." is shown.

**Comment by reneeb** [comment]
1) is for backwards compatibility ;-)

2) I will provide a commit for that.

**Comment by dennykorsukewitz** [comment]
Hi @reneeb @jepf,

What is the status here?

**Comment by reneeb** [comment]
@dennykorsukewitz I added the check for 'module' parameters when the selected mode is 'single'. So this should be done...

**Comment by dennykorsukewitz** [comment]
Hi @jepf 
that looks good to me so far.
Do you have anything else?

**Review by dennykorsukewitz — APPROVED** [review]

**Review by jepf — APPROVED** [review]

**Pull request merged**
