### PR TITLE
Sector Nord AG: Added Sysconfig options to define font sizes, font names and plugins to CKEditor

### PR DESCRIPTION
**Pull request by jross93**
## Proposed change

Some of our customers miss the font size 14px or the font name Calibri. Moreover it should be configurable for the customer to define all font sizes and font names that can be selected in the CKEditor.

Changes:
- Added font size 14px
- Added font name Calibri
- Added option in Sysconfig to define all selectable font sizes
- Added option in Sysconfig to define all selectable font names
- Added option in Sysconfig to define all plugins for the CKEditor

## Type of change

- '1 - 🚀 feature'  

## Additional information

The Sysconfig options are:

- Frontend::RichTextFontNames
- Frontend::RichTextFontDefault
- Frontend::RichTextFontSizes

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by dennykorsukewitz** [comment]
Hi @jsinagowitz,

before I look at the code in detail, I would like to make a wish. 🎁 💫

As the richtexteditor has some settings and probably more will be added, it makes sense to me that this should be as simple as possible for the future.

Can you please change the code so that we only have to add SysConfigs.

For example like this:
`Frontend::RichText###TextDirection`
`Frontend::RichText###FontSizes`

Of course, it would be nice if you could then adapt the existing configurations to the new structure. 🚀 

The code would then become shorter and more clearer.

I am excited. 😄 
Happy hacking

**Comment by jross93** [comment]
Hi @dennykorsukewitz 

thank you for your ideas. Unfortunatly there is already a setting `Frontend::RichText` (checkbox) to control if RichText is enabled globally. The config can't be a value and hash at the same time.
I can eather update all `Frontend::RichText` to `Frontend::RichText###Enabled` (or something like that) or update the `Frontend::RichText###...`-Settings to `Frontend::RichText::Settings###...` (or something like that). 
What would you prefer?

**Comment by dennykorsukewitz** [comment]
Hi @jsinagowitz ,

sorry for the delay.
I've had another look at it.
You are right about the string vs. hash problem.

If we put the SysConfig in this form `Frontend::RichText###Enabled` then this is the best way forward. But unfortunately the additional effort is too great and no longer fits the PullRequest.

We will do the following:

# First step

Please change your SysConfig names to the following:

    Frontend::RichText::
    Frontend::RichTextFontSizes => Frontend::RichText::FontSizes
    Frontend::RichTextFontNames => Frontend::RichText::FontNames
    Frontend::RichTextExtraPlugins => Frontend::RichText::ExtraPlugins

# Second step
    
We change the SysConfig in an internal process.

    Frontend::RichText###NAME


Thanks 🚀

**Comment by jross93** [comment]
Hi @dennykorsukewitz 

sorry for the delay. 
I like the idea with the iteration so I just put it in. 
Refactoring the setting 'Frontend::RichText' would change many modules, so I renamed the new settings to `Frontend::RichText::Settings###...` for now.

Please have a look! 😄

**Comment by jross93** [comment]
Hi @dennykorsukewitz 
any news to this PR?
Another one of our customers requested this change. 
I understand that you are currently busy, maybe you can change the label "wait for contributor" to prevent oblivion.

Best regards

**Comment by eyazi** [comment]
I really like this idea – great PR. It would be great to see this function in Znuny.
If I could make a wish: It would also be great to have support for extraAllowedContent to also allow tags and attributes you might want to use in the Editor.

Please let me know if there is anything I can help with.

**Comment by jepf** [comment]
@jsinagowitz 

Sorry for the delay. I would like to test and merge this but it now has merge conflicts. Would you be so kind to resolve these? I know it's not your fault 😉

**Comment by jross93** [comment]
The pull request got merged automatically after I reverted my branch. I just created #285

**Comment by dennykorsukewitz** [comment]
@jepf @jsinagowitz this is strange. This MR is merged without changes...
This sounds more like a bug at GitHub than as desired.

**Pull request merged**
