### PR TITLE
Sector Nord AG: Added Sysconfig options to control more settings of CKEditor

### PR DESCRIPTION
**Pull request by jross93**
## Proposed change

(This pull request belongs to #183. The old pull request got merged automatically after I reverted my branch.)

Some of our customers miss the font size 14px or the font name Calibri. Moreover it should be configurable for the customer to define all font sizes and font names that can be selected in the CKEditor.

Changes:
- Added font size 14px
- Added font name Calibri
- Added option in Sysconfig to define all selectable font sizes
- Added option in Sysconfig to define all selectable font names
- Added option in Sysconfig to define all plugins for the CKEditor
- Added option in Sysconfig to define extraAllowedContent (as requested from @eyazi in #183)

## Type of change

- '1 - 🚀 feature'  

## Additional information

The Sysconfig options are:

- Frontend::RichText::Settings###FontSizes
- Frontend::RichText::Settings###FontNames
- Frontend::RichText::Settings###ExtraPlugins
- Frontend::RichText::Settings###ExtraAllowedContent

"::Settings" were added because "Frontend::RichText" can't be a checkbox and a hash at once.

- This PR is related to PR: #183 

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Review by dennykorsukewitz — APPROVED** [review]

**Comment by dennykorsukewitz** [comment]
internal MR 599

**Comment by dennykorsukewitz** [comment]
Hi @jsinagowitz,

could you please check out the current version and fix the failing unit tests since this PR is merged:
https://github.com/znuny/Znuny/commit/e67777063001cdb093b3506b73746218d8497d40

1. create a issue
2. create pull-request 

```
7 tests failed.
 FailedTests:
  /opt/otrs/scripts/test/Selenium/Agent/AgentTicketActionCommon/AgentTicketNote.t #83 - WaitFor
  /opt/otrs/scripts/test/Selenium/Agent/AgentTicketProcessAttachment.t #44 - Attachment is created in process ticket article
  /opt/otrs/scripts/test/Selenium/Agent/AgentTicketSplitInlineImage.t #38 - WaitFor
  /opt/otrs/scripts/test/Selenium/Agent/AgentValidateCKEditor.t #18 - WaitFor
  /opt/otrs/scripts/test/Selenium/Agent/CKEditor.t #16 - WaitFor
  /opt/otrs/scripts/test/Selenium/Agent/FormDraft/AgentTicketActionCommonDraft.t #24 - WaitFor
  /opt/otrs/scripts/test/Selenium/Agent/MultiAttachmentUpload/CommunicationScreens.t #59 - Error while executing command: clickElement: element not interactable
  ```
https://github.com/znuny/Znuny/actions/runs/3142859278

I have seen too late that these do not go through successfully.
Give me quick feedback so i know you are working on it. 👍🏼 

Thanks 🚀

**Comment by jross93** [comment]
Hi @dennykorsukewitz 

unfortunately I can not replicate the unittest issue on my virtual machine. I checked out the commit c677770.
I double checked that the changes (e.g. in Core.UI.RichTextEditor.js) are installed. Is there anything that I can do? I already rebuild the config and the js cache.

```
[root@js-test otrs]# sudo -u otrs bin/otrs.Console.pl Dev::UnitTest::Run --test CKEditor
+-------------------------------------------------------------------+
  /opt/otrs/scripts/test/Selenium/Agent/CKEditor.t:
+-------------------------------------------------------------------+
...
/opt/otrs/scripts/test/Selenium/Agent/CKEditor.t ran 3 test(s) in 0.080s.

=====================================================================
yourhost.example.com ran 3 test(s) in 0.255s for Znuny 6.4.x.
All 3 tests passed.
[root@js-test otrs]# sudo -u otrs bin/otrs.Console.pl Dev::UnitTest::Run --test AgentTicketSplitInlineImage
+-------------------------------------------------------------------+
  /opt/otrs/scripts/test/Selenium/Agent/AgentTicketSplitInlineImage.t:
+-------------------------------------------------------------------+
...
/opt/otrs/scripts/test/Selenium/Agent/AgentTicketSplitInlineImage.t ran 3 test(s) in 0.097s.

=====================================================================
yourhost.example.com ran 3 test(s) in 0.259s for Znuny 6.4.x.
All 3 tests passed.
[root@js-test otrs]# sudo -u otrs bin/otrs.Console.pl Dev::UnitTest::Run --test AgentTicketNote
+-------------------------------------------------------------------+
  /opt/otrs/scripts/test/Selenium/Agent/AgentTicketActionCommon/AgentTicketNote.t:
+-------------------------------------------------------------------+
...
/opt/otrs/scripts/test/Selenium/Agent/AgentTicketActionCommon/AgentTicketNote.t ran 3 test(s) in 0.093s.

=====================================================================
yourhost.example.com ran 3 test(s) in 0.249s for Znuny 6.4.x.
All 3 tests passed.
[root@js-test otrs]# sudo -u otrs bin/otrs.Console.pl Dev::UnitTest::Run --test CommunicationScreens
+-------------------------------------------------------------------+
  /opt/otrs/scripts/test/Selenium/Agent/MultiAttachmentUpload/CommunicationScreens.t:
+-------------------------------------------------------------------+
...
/opt/otrs/scripts/test/Selenium/Agent/MultiAttachmentUpload/CommunicationScreens.t ran 3 test(s) in 0.107s.

=====================================================================
yourhost.example.com ran 3 test(s) in 0.268s for Znuny 6.4.x.
All 3 tests passed.
```

**Comment by dennykorsukewitz** [comment]
Hi @jsinagowitz ,

I understand...Currently there seems to be a difference between the local instances and the one on GitHub.
Maybe you can get this out with a fork on GitHub.

As you can see, the tests always fail the same way.
Maybe you can rebuild the code piece by piece and see where the error is or get closer to the error with dumper.
Maybe it is just a configuration that is different on GitHub than local.

I know this is hard.
Maybe another colleague from Sector Nord has an idea?

I keep my fingers crossed.🚀

**Comment by tipue-dev** [comment]
This seems to be a timing problem. The Screenshots show a missing CKEditor.
If i run the test locally, you can see in the video (very slowed down), that at the point where the test fails, the editor just becomes visible.
Maybe the new config in combination with a relatively slow GitHub runner (and maybe also the new ``disable-gpu`` argument) makes is just slow enough to fail.


https://user-images.githubusercontent.com/80031303/194393032-d939086f-d4b9-4378-805a-bc39bf5a328f.mp4

**Comment by dennykorsukewitz** [comment]
Thank you @tipue-dev for the good analysis.

I have not yet been able to reproduce it locally either.
Long time ago we had included 'disable-gpu' in the config by default for our Windows colleagues. 
This of course makes no sense on GitHub and can be removed.
Nevertheless, the initialization process seems to be slower than before.

The WaitFor function should actually ensure that the editor is loaded.
```perl
$Selenium->WaitFor(
    JavaScript => "return typeof(\$) === 'function' && \$('body.cke_editable', \$('.cke_wysiwyg_frame').contents()).length == 1"
);
```

**Comment by tipue-dev** [comment]
@dennykorsukewitz yes, and even a 10 second delay before that function (that is the one failing) doesn't work. There is something else wrong

**Comment by dennykorsukewitz** [comment]
Hi @jsinagowitz,

thank you very much for your help. 👍🏼 

🚀

**Pull request merged**
