### PR TITLE
Ticket email delivery failure notification template initialization fix

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change
In OTRS CE 6 new notification "Ticket email delivery failure notification"
was introduced with e-mail template set to Default which is inconsistent with
other e-mail notification templates in system (which do not specify email
template and allow system to use template set
in NotificationEmailDefaultTemplate sysconfig parameter).

This mod fixes it (new notification will initialize template same way
as other notifications).

This mod does not change data in existing installations (will
apply only to new 6+ installations and new upgrades to 6).

## Type of change
- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Additional information

Author-Change-Id: IB#1109073

## Checklist

- [x] The code change is tested and works locally.(❗)
- [ ] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
@pboguslawski I'm sorry, but we did not find a system configuration with the name `NotificationEmailDefaultTemplate`. We're have you seen/found this?

**Comment by pboguslawski** [comment]
> @pboguslawski I'm sorry, but we did not find a system configuration with the name `NotificationEmailDefaultTemplate`. We're have you seen/found this?

This parameter was contributed in https://github.com/OTRS/otrs/pull/1081 but previous upstream did't merge it. Consider introducing this parameter into Znuny.

Even if you don't want  `NotificationEmailDefaultTemplate`, please consider merging this PR for notification definition consistency (other templates don't set Default on init in DB).

**Comment by dennykorsukewitz** [comment]
Hi

This branch has conflicts that must be resolved.

Thank you! :rocket:

**Comment by pboguslawski** [comment]
Replaced by https://github.com/znuny/Znuny/pull/397

**Pull request closed without merging**
