### PR TITLE
Sector Nord AG: Added Attachments to TransitionAction TicketCreate

### PR DESCRIPTION
**Pull request by LuBroering**
## Proposed change

Added feature for TransitionAction TicketCreate that will provide the user with the option to add attachments to a SubTicket.
Provided by Sector Nord AG as discussed with Roy Kaldung (@rkaldung) and Henrik Vetter (@Tronsy).

## Type of change

- '1 - 🚀 feature' 
## Additional information

This parameter is optional.
To use it, add a key-value-pair to the TicketCreate TransitionAction where key is 'Attachments' and value is (1|y|yes). 

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [x] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by MarcPahnke** [comment]
Hi guys - @rkaldung, @jepf and of course @LuBroering ,
regarding the failed unit test: It seems that 
the new settings already included in this PR in file Kernel/Config/Files/XML/ProcessManagement.xml line 401..407 were not applied before the unit test run. So either the unit test has to be changed so that it creates the necessary config entries and the corresponding Dynamic field inside of the test. Or a small "unit test preparation-script" run, which updates the database (creates the DynamicField according the scripts/MigrateToZnuny6_1/UpgradeDatabaseStructure.pm within this PR) and applies all the new SysConfig entries, has to created. 
Or is simply the step-order in the build pipeline incorrect in this case? - In our internal gitlab pipeline, which is a little bit different of course, it works.
What - or how - can we solve this? Any thoughts - proposals?

Regards, Marc

**Comment by dennykorsukewitz** [comment]
Hi @LuBroering,
@MarcPahnke ,


```
+-------------------------------------------------------------------+
  /opt/otrs/scripts/test/ProcessManagement/TransitionAction/TicketCreateAttachment.t:
+-------------------------------------------------------------------+
..........................................................
 not ok 59 - Got DynamicField -  ''

 not ok 60 - ERROR: Error in /opt/otrs/scripts/test/ProcessManagement/TransitionAction/TicketCreateAttachment.t: Couldn't get no Dynamic Field named: 'ProcessManagementAttachment' at (eval 411) line 341.

.
/opt/otrs/scripts/test/ProcessManagement/TransitionAction/TicketCreateAttachment.t ran 61 test(s) in 0.515s.
```
The dynamic field `ProcessManagementAttachment` does not currently exist.

To save some time, I will take the code as it is, without any further code suggestions. 
However, I will change some things.

- [ ] SysConfig for optional emptying of the dynamic field ProcessManagementAttachment
- [ ] SysConfig for formatting the output (html select options) (FormatString) as sprintf format. `'#%1$d: %5$s';` See: AgentTicketProcess.pm
- [ ] Fix UnitTest
- [ ] Add additional function to get Attachments in Base.pm
...

I hope that's all right with you.
I would be happy if you would take a look at my changes and give me feedback.

Thanks for the really cool pull request. :rocket: :smiley:

**Comment by dandanpena** [comment]
Sorry if Im not supposed to comment here, but the file **scripts/test/ProcessManagement/TransitionAction/TicketCreateAttachment.t** at line 59 has no ";" and line 60 is commented out:
```
my $AttachmentsDynamicFieldName = $ConfigObject->Get('Process::DynamicFieldProcessManagementAttachment')
    // 'ProcessManagementAttachment';
```
Is it correct?

**Comment by dennykorsukewitz** [comment]
``> Sorry if Im not supposed to comment here, but the file **scripts/test/ProcessManagement/TransitionAction/TicketCreateAttachment.t** at line 59 has no ";" and line 60 is commented out:
> 
> ```
> my $AttachmentsDynamicFieldName = $ConfigObject->Get('Process::DynamicFieldProcessManagementAttachment')
>     // 'ProcessManagementAttachment';
> ```
> 
> Is it correct?

Thank you for your attention. 👀  👍🏼 
But in this case everything is correct. 🆗 
In Perl you can write multiple lines.

```perl
# This is a comment in Perl.

# If SysConfig is not defined or empty use this String `ProcessManagementAttachment`
// 'ProcessManagementAttachment';
```

We are very pleased.
So stay tuned! 👍🏼

**Pull request merged**
