### PR TITLE
Fixed remove of mention and unnecessary errors in the log

### PR DESCRIPTION
**Pull request by tipue-dev**
## Proposed change
Mentioning an agent results in errors in the log. While trying to cut the list of mentioned agents, the new array gets filled with ```undef``` for as many users are missinng to reach the maximum number given by %Param.
image

Using the eye in the right corner to remove a mention results in an error, because no user id is send with the removal request.
image

Additionally, removing a mention from AgentTicketZoom let's the page jump to the top before the page is refreshed. 

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [ ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by KaiHerlemann** [comment]
I've reviewed the changes, the issues no longer occur.

**Comment by tipue-dev** [comment]
> I've reviewed the changes, the issues no longer occur.

@KaiHerlemann which issue are you referring to? This PR fixed three unconnected issues

Edit: is just saw, that you said 'issues' and not 'issue'. I tested the logging when mentioning a group and the problem still exists.

**Comment by KaiHerlemann** [comment]
> > I've reviewed the changes, the issues no longer occur.
> 
> @KaiHerlemann which issue are you referring to? This PR fixed three unconnected issues
> 
> Edit: is just saw, that you said 'issues' and not 'issue'. I tested the logging when mentioning a group and the problem still exists.

@tipue-dev I didn't have the logging issue, even if I was mentioning a group. 
However, "Additionally, removing a mention from AgentTicketZoom let's the page jump to the top before the page is refreshed." - I still have this problem, I didn't notice it at first.

**Comment by tipue-dev** [comment]
> > > I've reviewed the changes, the issues no longer occur.
> > 
> > 
> > @KaiHerlemann which issue are you referring to? This PR fixed three unconnected issues
> > Edit: is just saw, that you said 'issues' and not 'issue'. I tested the logging when mentioning a group and the problem still exists.
> 
> @tipue-dev I didn't have the logging issue, even if I was mentioning a group. However, "Additionally, removing a mention from AgentTicketZoom let's the page jump to the top before the page is refreshed." - I still have this problem, I didn't notice it at first.

@KaiHerlemann try mentioning a group with one person or so, so that you are definitely under the limit of people that can get a mention. How many people where in your group?

**Comment by tipue-dev** [comment]
I removed the part for removing Agents from the mention list, because that was fixed by now. My fix for the jumping on the page was for the mention-ticket-list instead of ticket zoom. I added this for the ticket zoom also.

**Comment by KaiHerlemann** [comment]
In our Microsoft Teams session we couldn't clarify why the problem with unnecessary errors in the system log does not occur for me when the PR is merged, but for @tipue-dev it does. Therefore, I created an internal issue 422.

**Comment by eyazi** [comment]
Just tested this on a blank system. Getting the same errors.

I'd even suggest this change, which I find a bit more readable:

```    MENTIONEDUSER:
    for my $MentionedUser (@MentionedUsers) {
        next MENTIONEDUSER if $UniqueMentionedUsers{$MentionedUser};
        last MENTIONEDUSER if @UniqueMentionedUsers > $Param{Limit};

        $UniqueMentionedUsers{$MentionedUser} = 1;

        push @UniqueMentionedUsers, $MentionedUser;
    }

    my $MentionedUserIDs = $Self->_GetMentionedUserIDs(
        MentionedUsers => \@UniqueMentionedUsers,
    );
```

**Comment by KaiHerlemann** [comment]
There was a misunderstanding regarding the system log, the issue is fixed by @tipue-dev's change (also by @eyazi's one - @dennykorsukewitz, maybe we should use this code?).
The second issue (no possibility to remove mentions by bulk action via mention view link) was solved in the meantime by [this](https://github.com/znuny/Znuny/commit/27f2bed9b5bf4b23b26e9f2d882372ec524e8515) change.

The issues of page jumps to the top after removing a mention, in case of both using the delete button on AgentTicketMentionView and AgentTicketZoom, are also solved.

**Comment by dennykorsukewitz** [comment]
Hi  @tipue-dev ,
thanks for your PR.

Please, keep your fork up-to-date with the upstream repository. 
[Syncing a fork 🚀  🆙 ](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)

I'll take another look at this PR after the sync.

Regards :rocket:
Denny

**Review by NiklasSchmitt — APPROVED** [review]
I'm sorry for the delay. I've tested and reviewed it today. Approved :rocket:

**Comment by NiklasSchmitt** [comment]
cherry-picked also in Znuny LTS. Will be part of the next Znuny LTS version 6.5.4: https://github.com/znuny/Znuny/commit/bd60690d3fe84028d2cd5d124280a5db1f1fadd9

**Pull request merged**
