### PR TITLE
Hide all password fields when backend without db pass is used

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

When using auth backend that does not require password from db (i.e.
basic auth) Znuny hides correctly password input in agent and customer
preferences (Kernel/Output/HTML/Preferences/Password.pm) but does not
hide password fields in AdminUser nor AdminCustomerUser screens. This
mod hides password fields on these screens also.

## Type of change
- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Additional information

Author-Change-Id: IB#1110411

## Checklist

- [x] The code change is tested and works locally.(❗)
- [ ] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [ ] GitHub workflow ZnunyCodePolicy passes.(❗)
- [ ] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
@pboguslawski I will close this PR due these reasons:
- You change behavior in the 6.0.x branch without knowing what are the side effects. I know at least 2 authentication backends which rely on this field.
- The regular expression you use is the one from the password preference. There is taken care that multiple authentication backends can be used and the preference is only shown if the agent/customer user has not used LDAP, HTTPBasicAuth or the Radius authentication. I don't see any kind of code like this in your PR. It needs to work in mixed environments.

If you just want the field not displayed for customer user it is sufficient to remove it from the mapping of the CustomerUser backend. It's only displayed if there is a field `UserPassword`: https://github.com/znuny/Znuny/blob/rel-6_0/Kernel/Modules/AdminCustomerUser.pm#L1139

**Comment by pboguslawski** [comment]
> I know at least 2 authentication backends which rely on this field.

As you can see in code this mod does not affect backends other than LDAP|HTTPBasicAuth|Radius. Do you see any problem with this mod for these 3 backends?

> I don't see any kind of code like this in your PR. It needs to work in mixed environments.

This PR hides password fields in admin module in _only_ when pass fields are _also_ hidden in preferences. Is there any reason to keep these fields available in admin module when its not available in preferences?

> If you just want the field not displayed for customer user it is sufficient to remove it from the mapping of the CustomerUser backend.

This PR uses the same algo for detecting when to hide password field as existing code Kernel/Output/HTML/Preferences/Password.pm. You propose different solution but only for customer users - not for agents. Don't see any reason for implementing it this way; more: leaving pass preference in db seems safer (in case of migration auth backends in both directions in system lifetime).

Consider reopening and merging this PR.

**Comment by rkaldung** [comment]
> > I know at least 2 authentication backends which rely on this field.
> 
> As you can see in code this mod does not affect backends other than LDAP|HTTPBasicAuth|Radius. Do you see any problem with this mod for these 3 backends?

Yes, there are e.g. LDAP implementations which allow to set the password.

> 
> > I don't see any kind of code like this in your PR. It needs to work in mixed environments.
> 
> This PR hides password fields in admin module in _only_ when pass fields are _also_ hidden in preferences. Is there any reason to keep these fields available in admin module when its not available in preferences?

if you create a new agent or customer user there are no preferences to check against. And you need to take into account that multiple authentications backend are allowed. They are daisy chained.


> > If you just want the field not displayed for customer user it is sufficient to remove it from the mapping of the CustomerUser backend.
> 
> This PR uses the same algo for detecting when to hide password field as existing code Kernel/Output/HTML/Preferences/Password.pm. You propose different solution but only for customer users - not for agents. Don't see any reason for implementing it this way; more: leaving pass preference in db seems safer (in case of migration auth backends in both directions in system lifetime).

As I mentioned earlier, chaining authentication is allowed and possible. That's why the authentication backend which is saved in the preferences is the last used method and not the only available for a agent/customer user.
 
> Consider reopening and merging this PR.
Sorry, as long as this breaks the current behavior the PR won't be worked on.

**Comment by pboguslawski** [comment]
> Yes, there are e.g. LDAP implementations which allow to set the password.

How it's possible in Znuny with current https://github.com/znuny/Znuny/blob/dev/Kernel/Output/HTML/Preferences/Password.pm#L54 which disables password preference (and user/customer cannot set/change their pass?).

If user is authenticated with LDAP - what's the sense of maintaining another pass in Znuny DB?

> And you need to take into account that multiple authentications backend are allowed. They are daisy chained.

We're avare of multiple user/customer user backends but still see no sense in disabling access to password self maintenance (preferences) and leaving it in admin module. If you see sensible scenario consider describing it - we analyze it and consider adjusting this mod if possible, safe and consistent.

**Comment by rkaldung** [comment]
> > Yes, there are e.g. LDAP implementations which allow to set the password.
> 
> How it's possible in Znuny with current https://github.com/znuny/Znuny/blob/dev/Kernel/Output/HTML/Preferences/Password.pm#L54 which disables password preference (and user/customer cannot set/change their pass?).
> 
> If user is authenticated with LDAP - what's the sense of maintaining another pass in Znuny DB?

Some setups have LDAP and DB authenticated agents. 
> 
> > And you need to take into account that multiple authentications backend are allowed. They are daisy chained.
> 
> We're avare of multiple user/customer user backends but still see no sense in disabling access to password self maintenance (preferences) and leaving it in admin module. If you see sensible scenario consider describing it - we analyze it and consider adjusting this mod if possible, safe and consistent.

See my comments above. It's changing existing behavior in the LTS version; depite that: any kind of implementation for 6.1 or later needs to cover all aspects.

**Pull request closed without merging**
