### PR TITLE
Fixed handling whitespaces around '=' in Content-Type/charset token.

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

This mod allowes Znuny to handle spaces around = in Content-Type/charset
like in message below:

    Return-Path: <test@test.loc>
    Date: Wed, 30 Apr 2014 12:04:07 +0200
    From: test <test@test.loc>
    To: <test@test.loc>
    Subject: test
    MIME-Version: 1.0
    Content-Type: text/plain; charset = "utf-8"
    Content-Transfer-Encoding: 8bit
    Message-ID: <test1003@test.loc>

    żółw

Extra spaces are tolerated by http://tools.ietf.org/tools/msglint/
validator (warnings only) and e-mail clients like Mozilla Thunderbird;
Znuny should allow it too to avoid problems (i.e. errors in syslog)
with e-mail messages using spaces as above. 

## Type of change
- '1 - 🐞 bug 🐞'            - Bugfix (non-breaking change which fixes an issue)

## Additional information

- Author-Change-Id: IB#1015440

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [x] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

**Comment by rkaldung** [comment]
Hi @pboguslawski,

Please follow the [contributing guidelines](https://github.com/znuny/Znuny/blob/rel-6_0-dev/CONTRIBUTING.md) and use the pull request template. And also, please point out if this is a bug fix or a feature.

**Comment by pboguslawski** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

we have changed our rules regarding copyright.
We therefore ask you to remove your newly added copyrights.

```
Znuny is an open fork of an existing software.
So we have to respect the already given copyright of the original creators.

New files will be licensed using the AGPL Version 3. 
If you contribute code to the Znuny project you will get mentioned in the pull request incl. the commit, 
in CHANGES.md and in AUTHORS.md. 
We will not mention you in the file you provided or changed. 
Your work is highly appreciated and acknowledged but you contribute it to the project 
and your copyright will pass on to the fork itself.
```
https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#licensing-copyright-and-credits

**Comment by pboguslawski** [comment]
Done.

**Review by dennykorsukewitz — APPROVED** [review]
Hi  @pboguslawski ,
thanks for your PR.

Approved :+1:

Regards :rocket:

**Pull request merged**
