### PR TITLE
Automatic set of body and subject for TicketArticleCreate and automatic set of subject from ticket-title on agent ticket-close 🚀

### PR DESCRIPTION
**Pull request by schnudd31do3**
## Proposed change
Patched TicketArticleCreate.pm
Automatic creation of an article's body and subject from the content of a DynamicField_MyTextfield using TicketArticleCreate in the transistion-action. You only have to set for the body-key the value OTRS_TICKET_DynamicField_MyTextfield.

Patched AgentTicketActionCommon.pm
Automatic seting the article subject from the ticket title when the agent closes the ticket. For that you have to set in Ticket::Frontend::AgentTicketClose###Subject the value OTRS_TICKET_Title.

## Type of change
🚀
## Checklist

- [x ] The code change is tested and works locally.(❗)
- [x ] There is no commented out code in this PR.(❕)
- [ ] You improved or added new unit tests.(❕)
- [x ] Local ZnunyCodePolicy run passes successfully.(❕)
- [ ] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by rkaldung** [comment]
@schnudd31do3 I'm sorry be we can't accept this pull request.
There are a couple of reasons: first of all this is not a proper pull request. You changed some files locally and uploaded them. This results in the inability to see what you've [changed](https://github.com/znuny/Znuny/pull/69/files). The file TicketArticleCreate.pm lacks the correct package naming (filename must match the last part of package).
But the most important part is that you changed behavior. Since this is the long term support branch there is no possibility to add features and especially changing behavior to it.

**Comment by schnudd31do3** [comment]
Hello Roy,

my fixes meet requirements that have often been asked in the Internet forums and no one had a solution. Would you want this solution to be withheld from so many users?

My changes do not change the previously known and accustomed behavior. The changes only become active when defined keywords are used as values ​​that have already been included in the code.

I apologize for the inaccuracy in the process. It is because I have never done this before and have struggled to find my way around. Would it be possible to email you the files for review because I didn't get it the right way? Please give the good ideas a second chance.

Thanks.

**Comment by rkaldung** [comment]
Let's start with the transition action: I really don't see the need for this change because you still are able to use smart tags like <OTRS_TICKET_DynamicField_xx> and <OTRS_Ticket_Title> in transition actions:

image

Except from your concatenation, what look's pretty customized to me, this is already possible. Let me know if I missed your use case.

And in more than 15 years with this application I can remember being  asked to have the ticket title in the subject of the close action.  The only change what make sense to me would be passing the ticket data to the layout object to have the data available: https://github.com/znuny/Znuny/pull/69/files#diff-a8230edd4606e95ca60b621de186be1c83b4bdeed7fa915365d53b39083525acR1654

```perl
            $GetParam{Subject} = $LayoutObject->Output(
                Template => $Config->{Subject},
                Data => \%Ticket,
            );
```

And in the SysConfig you use `[% Data.Title | html %]` 

This is really something we could consider, but only for the upcoming feature release. It's to risky to break existing add-ons with this.


Thank you for your input so far!

**Comment by schnudd31do3** [comment]
Thanks for your reply. Before answering, I would like to know where to change the  „And in the SysConfig you use [% Data.Title | html %]“ and/or which parameter is it?

**Comment by schnudd31do3** [comment]
Hello,
in the meantime I found where to change the „[% Data.Title | html %]“. You additionally have to activate Ticket::Frontend::AgentTicketClose###Subject. So my suggest for adapting the AgentTicketActionCommon.pm is obsolete.

Unfortunately the TicketArticleCreate does not take the value for displaying. It only shows the name of the tag.
In the code you can find the location where „OTRS_TICKET_DynamicField_xx“ is analyzed. The code there only sorts the recognized DynamicFields. My code-extension is placed before sorting. It takes the value for displaying instead of the name of the DynamicField. Could you please check it?

Regards

**Comment by schnudd31do3** [comment]
Hello,
I was wrong with:
„Hello,
in the meantime I found where to change the „[% Data.Title | html %]“. You additionally have to activate Ticket::Frontend::AgentTicketClose###Subject. So my suggest for adapting the AgentTicketActionCommon.pm is obsolete.„

This adaption displays the ticket title but does not prefill the subject line oft he notice. Therefore I would like to keep my suggest for changing the AgentTicketActionCommon.pm

Regards

From: Volker Bäurer
Sent: Friday, May 7, 2021 7:39 AM
To: 'znuny/Znuny' ***@***.***>
Subject: RE: [znuny/Znuny] Automatic set of body and subject for TicketArticleCreate and automatic set of subject from ticket-title on agent ticket-close 🚀 (#69)

Hello,
in the meantime I found where to change the „[% Data.Title | html %]“. You additionally have to activate Ticket::Frontend::AgentTicketClose###Subject. So my suggest for adapting the AgentTicketActionCommon.pm is obsolete.

Unfortunately the TicketArticleCreate does not take the value for displaying. It only shows the name of the tag.
In the code you can find the location where „OTRS_TICKET_DynamicField_xx“ is analyzed. The code there only sorts the recognized DynamicFields. My code-extension is placed before sorting. It takes the value for displaying instead of the name of the DynamicField. Could you please check it?

Regards

**Comment by schnudd31do3** [comment]
Update (sorry for disturbing you):
I found with my extension of TicketArticleCreate.pm is working for the agent generating a notice and for closing th ticket. You have to overtake my extension and set:
Ticket::Frontend::AgentTicketClose###Subject
OTRS_TICKET_Title

Ticket::Frontend::AgentTicketNote###Subject
OTRS_TICKET_Title

Regards.

From: Volker Bäurer
Sent: Friday, May 7, 2021 9:32 AM
To: 'znuny/Znuny' ***@***.***>
Subject: RE: [znuny/Znuny] Automatic set of body and subject for TicketArticleCreate and automatic set of subject from ticket-title on agent ticket-close 🚀 (#69)

Hello,
I was wrong with:
„Hello,
in the meantime I found where to change the „[% Data.Title | html %]“. You additionally have to activate Ticket::Frontend::AgentTicketClose###Subject. So my suggest for adapting the AgentTicketActionCommon.pm is obsolete.„

This adaption displays the ticket title but does not prefill the subject line oft he notice. Therefore I would like to keep my suggest for changing the AgentTicketActionCommon.pm

Regards

From: Volker Bäurer
Sent: Friday, May 7, 2021 7:39 AM
To: 'znuny/Znuny' ***@***.******@***.***>>
Subject: RE: [znuny/Znuny] Automatic set of body and subject for TicketArticleCreate and automatic set of subject from ticket-title on agent ticket-close 🚀 (#69)

Hello,
in the meantime I found where to change the „[% Data.Title | html %]“. You additionally have to activate Ticket::Frontend::AgentTicketClose###Subject. So my suggest for adapting the AgentTicketActionCommon.pm is obsolete.

Unfortunately the TicketArticleCreate does not take the value for displaying. It only shows the name of the tag.
In the code you can find the location where „OTRS_TICKET_DynamicField_xx“ is analyzed. The code there only sorts the recognized DynamicFields. My code-extension is placed before sorting. It takes the value for displaying instead of the name of the DynamicField. Could you please check it?

Regards

**Pull request closed without merging**
