### PR TITLE
Disable connecting external RSS during unit testing

### PR DESCRIPTION
**Pull request by pboguslawski**
## Proposed change

External RSS service is called during frontend unit
tests. This mod disables connecting external RSS in
these test to avoid slowing down tests in environments
where calling external services is prohibited.

## Additional information

- Internal info leaking is a bug so this PR is bugfix in our opinion.
- Author-Change-Id: IB#1107930

## Checklist

- [x] The code change is tested and works locally.(❗)
- [x] There is no commented out code in this PR.(❕)
- [x] You improved or added new unit tests.(❕)
- [x] Local ZnunyCodePolicy run passes successfully.(❕)
- [x] Local unit tests pass.(❕)
- [x] GitHub workflow ZnunyCodePolicy passes.(❗)
- [x] GitHub workflow unit tests pass.(❗)

### CODE REVIEW

**Comment by pboguslawski** [comment]
BTW: other unit tests that try to call external services (cloud.otrs.com, znuny.org) may be disabled by adding

```
$Self->{'UnitTest::Blacklist'}->{'1000-DisableTestsWithUsingExternalResources'} = ['CloudService.t', 'Console/Command/Admin/Package/RepositoryList.t', 'Console/Command/Maint/CloudServices/ConnectionCheck.t', 'OTRSBusiness/EntitlementCheck.t', 'Package/ConfiguredRepositoryDefinitionGet.t', 'WebUserAgent.t'];
```

to Config.pm.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

can you please resolve the conflicts.
You do not need to adjust the CHANGES.md. We will do that afterwards for all merged PRs.

Thanks 🚀

**Comment by pboguslawski** [comment]
Removed entry to CHANGES.md.

**Comment by pboguslawski** [comment]
Updated PR description from template.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski,

we like the idea of disabling certain modules during unit testing.
However, we would like to make the idea a bit more global and variable.

We imagine something like `DisableAsyncCalls` for the `UnitTest::Helper`:

```perl
$Kernel::OM->ObjectParamAdd(
    'Kernel::System::UnitTest::Helper' => {
        RestoreDatabase   => 1,
        UseTmpArticleDir  => 1,
        DisableAsyncCalls => 1,
        DisableUNKOWNNAME => [
			'ModuleName',
			'or',
			'SysConfig'
		],
    },
);
```

Maybe you have time, fun and some ideas to build on this idea?

**Comment by pboguslawski** [comment]
> We imagine something like DisableAsyncCalls for the UnitTest::Helper

According to [your request](https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#how-to-contribute) this PR is bugfix (hammering external service during CI pipeline) and does not contain features.

> Maybe you have time, fun and some ideas to build on this idea?

Sorry, no time now for nice to have ideas. Feel free to extend solution from this PR to your liking if you see that `DisableAsyncCalls` is needed (we don't).

Regards,
Paweł

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski,

I meant DisableAsyncCalls as an example.
The naming can still be chosen.

```perl
$Kernel::OM->ObjectParamAdd(
    'Kernel::System::UnitTest::Helper' => {
        DisableModules => [
			'ModuleName',
			'or',
			'...'
		],
        DisableSysConfigs => [
			'SysConfig',
			'or',
			'...'
		],
    },
);
```


I understand that you do not have time.
But we are always happy about your pull requests.

I will discuss the further procedure for this pull request with my colleagues.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski 

we have changed our rules regarding copyright.
We therefore ask you to remove your newly added copyrights.

```
Znuny is an open fork of an existing software.
So we have to respect the already given copyright of the original creators.

New files will be licensed using the AGPL Version 3. 
If you contribute code to the Znuny project you will get mentioned in the pull request incl. the commit, 
in CHANGES.md and in AUTHORS.md. 
We will not mention you in the file you provided or changed. 
Your work is highly appreciated and acknowledged but you contribute it to the project 
and your copyright will pass on to the fork itself.
```
https://github.com/znuny/Znuny/blob/rel-6_1-dev/CONTRIBUTING.md#licensing-copyright-and-credits

**Comment by pboguslawski** [comment]
Done.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski ,

can you please make some adjustments.

As discussed above, we have included a `DisableSysConfigs` [function into helper.](https://github.com/znuny/Znuny/commit/2545390a0535aec674644455c4336c23b4f4916b)

Please include this code accordingly [here](https://github.com/znuny/Znuny/blob/dev/scripts/test/Frontend/Basic.t#L25) and resolve the conflicts.

```perl
$Kernel::OM->ObjectParamAdd(
    'Kernel::System::UnitTest::Helper' => {
        SkipSSLVerify     => 1,
        DisableAsyncCalls => 1,
        DisableSysConfigs => [
            'DashboardBackend###0442-RSS'
        ],
    },
);

```
Let us know if you don't want to make any more changes. 
Then i will close the PullRequest.

Thx 🚀

**Comment by pboguslawski** [comment]
This PR was made for rel-6_0 and your mod is not present there. Connecting to external RSS during unit tests should be disabled in rel-6_0 also. Consider fixing it there using this PR or backport your fix and then close this PR.

**Comment by dennykorsukewitz** [comment]
Hi @pboguslawski,

that is correct. After you did not have time to create the desired codechanges (helper). I have done this.
I had hoped that you as a community member could take over the backport. 

#community

**Review by dennykorsukewitz — APPROVED** [review]

**Pull request merged**
